---


# ---------------------------------------------- Setup rally
- name: Create rally result directory
  file:
    path: "/root/rally_home"
    state: directory
    owner: 65500

- name: Test whether the rally database has been initialized
  stat: path=/root/rally_home/rally.db
  register: sqlite

- name: Initialize database
  command: >
    docker run -v /root/rally_home:/home/rally/data \
    beyondtheclouds/xrally-openstack:dev \
    db create
  when:
    - not sqlite.stat.exists

# NOTE(msimonin): without the pause
# the file seems not to be synced in the next task.
# Relaunching the play a second time is also a possible wokaround.
- name: Waiting a few seconds
  pause: seconds=5

- name: Test whether the rally deployment has been created
  command: >
    docker run -v /root/rally_home:/home/rally/data \
    beyondtheclouds/xrally-openstack:dev \
    deployment list
  register: deployment

- name: Deploy discovery context
  docker_container:
    name: "rally-{{ inventory_hostname_short }}"
    image: "beyondtheclouds/xrally-openstack:dev"
    state: started
    volumes:
      - /root/rally_home:/home/rally/data
    env: "{{ os_env }}"
    command: deployment create --fromenv --name=discovery
  when:
    - "'discovery' not in deployment.stdout"


# ----------------------------------- Setup & run rally test

# When --file was used
- name: Preparing the files
  include: deploy-files.yml
  when:
    - rally_files is defined

# When --directory was used (default option with keystone)
- name: "Preparing the files in directory: {{ rally_directory }}"
  include: deploy-directory.yml
  when:
    - rally_files is not defined
    - rally_directory is defined

# When --tasks was used
- name: Preparing the tasks
  include: deploy-task.yml
  when:
    - rally_tasks is defined

# Final run
- name: Include run scenarios
  include: rally-scenarios.yaml


# -------------------------------- Download results (if any)

- name: Find report identifier
  command: >
    docker run -v /root/rally_home:/home/rally/data \
    beyondtheclouds/xrally-openstack:dev \
    task list --uuids-only \
    --deployment discovery
  register: task_uuid

- name: Generating rally reports (html)
  command: >
    docker run -v /root/rally_home:/home/rally/data \
    beyondtheclouds/xrally-openstack:dev \
    task report --uuid {{ item }} \
    --html-static --out \
    /home/rally/data/report-{{ item }}.html
  with_items: "{{ task_uuid.stdout_lines }}"
  when:
    - task_uuid.stdout != ""

- name: Generating rally reports (json)
  command: >
    docker run -v /root/rally_home:/home/rally/data \
    beyondtheclouds/xrally-openstack:dev \
    task report --uuid {{ item }} \
    --json --out \
    /home/rally/data/report-{{ item }}.json
  with_items: "{{ task_uuid.stdout_lines }}"
  when:
    - task_uuid.stdout != ""
