- name: files - Specify the scenarios which will be used
  debug:
    msg: "Launching following scenarios: {{ rally_files }}"

- name: Generate scenario execution playboook
  template:
    src: rally-scenarios.yaml.j2
    dest: ./rally-scenarios.yaml
  run_once: True
  delegate_to: 127.0.0.1
  with_list:  "{{ [rally_files] }}"
