---
- name: Create CockroachDB sbtest database for sysbench
  command: >
    docker exec cockroachdb-{{ inventory_hostname_short }}
           ./cockroach sql
               --execute "CREATE DATABASE IF NOT EXISTS sbtest ENCODING = 'UTF8'"
               --insecure
  when:
    - inventory_hostname == dbmaster_node
