---
- name: Tar sysbench results
  archive:
    path:
      - /sysbench
    dest: "/sysbench-{{ inventory_hostname_short }}.tar.gz"

- name: Fetch rally data
  fetch:
    src: "/sysbench-{{ inventory_hostname_short }}.tar.gz"
    dest: "{{ backup_dir }}/sysbench-{{ inventory_hostname_short }}.tar.gz"
    flat: yes
