---
- name: Remove /sysbench directory
  file:
    state: absent
    path: /sysbench

- name: Destroying sysbench container
  docker_container:
    name: "sysbench"
    state: absent
    force_kill: yes
